CREATE TABLE platform.spr_session (
   PRIMARY_ID CHAR(36) NOT NULL,
   SESSION_ID CHAR(36) NOT NULL,
   CREATION_TIME NUMERIC(19,0) NOT NULL,
   LAST_ACCESS_TIME NUMERIC(19,0) NOT NULL,
   MAX_INACTIVE_INTERVAL NUMERIC(10,0) NOT NULL,
   EXPIRY_TIME NUMERIC(19,0) NOT NULL,
   PRINCIPAL_NAME VARCHAR(100),
   CONSTRAINT spr_session_pk PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX spr_session_index ON platform.spr_session (SESSION_ID);
CREATE INDEX spr_session_ix2 ON platform.spr_session (EXPIRY_TIME);
CREATE INDEX spr_session_ix3 ON platform.spr_session (PRINCIPAL_NAME);

CREATE TABLE platform.spr_session_attributes (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES bytea NOT NULL,
    CONSTRAINT SPR_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPR_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID)
    REFERENCES platform.spr_session(PRIMARY_ID) ON DELETE CASCADE
 );